<?php

define("CLIENT_ID",		"GPP0FG0DZI3ES5JKLNBJWZDMEITYI2XECBVTSW2GL3ZJCHGT");
define("CLIENT_SECRET",	"5P3ABYS1CSVHXVEEAHWZP1A42DWZ4DTXROA5SAFCTXZCJNMX");

define("CITIZEN_STARTUP",5);
define("CITIZEN_INCREASE",2);

?>